export const TOOL_NAMES = {
  Agent: "Agent",
  AskUserQuestion: "AskUserQuestion",
  Bash: "Bash",
  CronCreate: "CronCreate",
  CronDelete: "CronDelete",
  CronList: "CronList",
  Edit: "Edit",
  EnterPlanMode: "EnterPlanMode",
  EnterWorktree: "EnterWorktree",
  ExitPlanMode: "ExitPlanMode",
  ExitWorktree: "ExitWorktree",
  Glob: "Glob",
  Grep: "Grep",
  ListMcpResourcesTool: "ListMcpResourcesTool",
  LSP: "LSP",
  NotebookEdit: "NotebookEdit",
  PowerShell: "PowerShell",
  Read: "Read",
  ReadMcpResourceTool: "ReadMcpResourceTool",
  SendMessage: "SendMessage",
  Skill: "Skill",
  TaskCreate: "TaskCreate",
  TaskGet: "TaskGet",
  TaskList: "TaskList",
  TaskOutput: "TaskOutput",
  TaskStop: "TaskStop",
  TaskUpdate: "TaskUpdate",
  TeamCreate: "TeamCreate",
  TeamDelete: "TeamDelete",
  TodoWrite: "TodoWrite",
  ToolSearch: "ToolSearch",
  WebFetch: "WebFetch",
  WebSearch: "WebSearch",
  Write: "Write",
}

export const TOOL_DESCRIPTIONS = {
  Agent: "Spawns a subagent with its own context window to handle a task",
  AskUserQuestion:
    "Asks multiple-choice questions to gather requirements or clarify ambiguity",
  Bash: "Executes shell commands in your environment",
  CronCreate:
    "Schedules a recurring or one-shot prompt within the current session",
  CronDelete: "Cancels a scheduled task by ID",
  CronList: "Lists all scheduled tasks in the session",
  Edit: "Makes targeted edits to specific files",
  EnterPlanMode: "Switches to plan mode to design an approach before coding",
  EnterWorktree: "Creates an isolated git worktree and switches into it",
  ExitPlanMode: "Presents a plan for approval and exits plan mode",
  ExitWorktree:
    "Exits a worktree session and returns to the original directory",
  Glob: "Finds files based on pattern matching",
  Grep: "Searches for patterns in file contents",
  ListMcpResourcesTool: "Lists resources exposed by connected MCP servers",
  LSP: "Code intelligence via language servers: definitions, references, type errors",
  NotebookEdit: "Modifies Jupyter notebook cells",
  PowerShell: "Executes PowerShell commands on Windows",
  Read: "Reads the contents of files",
  ReadMcpResourceTool: "Reads a specific MCP resource by URI",
  SendMessage:
    "Sends a message to an agent team teammate or resumes a subagent",
  Skill: "Executes a skill within the main conversation",
  TaskCreate: "Creates a new task in the task list",
  TaskGet: "Retrieves full details for a specific task",
  TaskList: "Lists all tasks with their current status",
  TaskOutput:
    "Retrieves output from a background task (deprecated, prefer Read)",
  TaskStop: "Kills a running background task by ID",
  TaskUpdate: "Updates task status, dependencies, details, or deletes tasks",
  TeamCreate: "Creates an agent team with multiple teammates",
  TeamDelete: "Disbands an agent team and cleans up teammate processes",
  TodoWrite:
    "Manages the session task checklist in non-interactive and Agent SDK modes",
  ToolSearch:
    "Searches for and loads deferred tools when tool search is enabled",
  WebFetch: "Fetches content from a specified URL",
  WebSearch: "Performs web searches",
  Write: "Creates or overwrites files",
}

/** @typedef {keyof typeof TOOL_NAMES} ToolName */
