// Re-export all types from the hand-authored declarations.
// This file overrides tsc-generated handler.d.mts in dist/ via the build
// copy step, ensuring imports of handler.mjs resolve to the precise
// generic signatures (including conditional return types and ToolInputMap).
export {
  HookHandler,
  HookIOMap,
  HookEventName,
  BaseHookOutput,
  PreToolUseOutput,
  PreToolUseHookSpecificOutput,
  PermissionRequestOutput,
  PermissionRequestDecision,
  PostToolUseOutput,
  PostToolUseFailureOutput,
  UserPromptSubmitOutput,
  NotificationOutput,
  StopOutput,
  SubagentStartOutput,
  SubagentStopOutput,
  PreCompactOutput,
  PostCompactOutput,
  SessionStartOutput,
  SessionEndOutput,
  SetupOutput,
  TeammateIdleOutput,
  TaskCreatedOutput,
  TaskCompletedOutput,
  ConfigChangeOutput,
  WorktreeCreateOutput,
  WorktreeRemoveOutput,
  InstructionsLoadedOutput,
  ElicitationOutput,
  ElicitationHookSpecificOutput,
  ElicitationResultOutput,
  ElicitationResultHookSpecificOutput,
  StopFailureOutput,
  CwdChangedOutput,
  FileChangedOutput,
  ToolInputMap,
  BashToolInput,
  WriteToolInput,
  EditToolInput,
  ReadToolInput,
  GlobToolInput,
  GrepToolInput,
  WebFetchToolInput,
  WebSearchToolInput,
  AgentToolInput,
  AskUserQuestionToolInput,
  type EnvVarReturnType,
} from "./handler-types.d.mts"

export type {
  HookHandlerMap,
  HookHandlerOptionsMap,
  EnvFileHandlerOptions,
  PreToolUseHookHandler,
  PermissionRequestHookHandler,
  PostToolUseHookHandler,
  PostToolUseFailureHookHandler,
  UserPromptSubmitHookHandler,
  StopHookHandler,
  SubagentStopHookHandler,
  TaskCreatedHookHandler,
  TaskCompletedHookHandler,
  NotificationHookHandler,
  SubagentStartHookHandler,
  PostCompactHookHandler,
  StopFailureHookHandler,
  ConfigChangeHookHandler,
  WorktreeCreateHookHandler,
  WorktreeRemoveHookHandler,
  InstructionsLoadedHookHandler,
  ElicitationHookHandler,
  ElicitationResultHookHandler,
  TeammateIdleHookHandler,
  SetupHookHandler,
  SessionStartHookHandler,
  SessionEndHookHandler,
  PreCompactHookHandler,
  CwdChangedHookHandler,
  FileChangedHookHandler,
} from "./handlers/index.d.mts"
